apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::633897975342:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11FPKXZQ5YUGH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::633897975342:role/testRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-17T00:26:03Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2021-03-17T00:26:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1563"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 50148fa4-5c56-4b42-ab20-d471ec624986
